[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
N8N_USER_MANAGEMENT_DISABLED=false
N8N_DEFAULT_USER_PASSWORD=Admin123456
N8N_DEFAULT_USER_EMAIL=admin@incaneurobaeza.com